# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_and_reg_app', '0003_auto_20191015_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='')),
                ('desc', models.TextField(max_length=100)),
                ('pieces_labeled', models.PositiveSmallIntegerField()),
                ('pieces_actual', models.PositiveSmallIntegerField()),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('missing_pieces', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(max_length=100)),
                ('owned', models.BooleanField(default=False)),
                ('completions', models.PositiveSmallIntegerField()),
                ('initial_complete', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='puzzle_app.Brand')),
                ('category', models.ManyToManyField(related_name='puzzles', to='puzzle_app.Category')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='log_and_reg_app.User')),
            ],
        ),
    ]
