# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='puzzle_app.Brand'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='category',
            field=models.ManyToManyField(default=None, related_name='puzzles', to='puzzle_app.Category'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='completions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='desc',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='height',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='initial_complete',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='length',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='missing_pieces',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='notes',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='owned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
