# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='owned_by',
            new_name='belongs_to',
        ),
    ]
