# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0002_auto_20191022_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='puzzle_app.Brand'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='category',
            field=models.ManyToManyField(null=True, related_name='puzzles', to='puzzle_app.Category'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='desc',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='initial_complete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='notes',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
