# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0003_auto_20191022_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='category',
            field=models.ManyToManyField(related_name='puzzles', to='puzzle_app.Category'),
        ),
    ]
