# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0004_auto_20191022_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='category',
            new_name='categories',
        ),
    ]
