# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0005_auto_20191022_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='length',
            new_name='width',
        ),
    ]
