# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0006_auto_20191022_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
