# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg_app', '0003_auto_20191015_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
