# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='helpers',
            field=models.ManyToManyField(null=True, related_name='projects', to='project_app.Helper'),
        ),
        migrations.AlterField(
            model_name='project',
            name='puzzles',
            field=models.ManyToManyField(null=True, related_name='projects', to='puzzle_app.Puzzle'),
        ),
        migrations.AlterField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
