# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-25 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20191024_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='helpers',
            field=models.ManyToManyField(related_name='projects', to='project_app.Helper'),
        ),
        migrations.AlterField(
            model_name='project',
            name='puzzles',
            field=models.ManyToManyField(related_name='projects', to='puzzle_app.Puzzle'),
        ),
    ]
